on: [push]
name: Inline.rs CI
jobs:
  build_and_test:
    name: Inline.rs CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Test build"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: "Running tests."
        uses: actions-rs/cargo@v1
        with:
          command: run